"""
AI IMAGE DETECTION SERVICE
===========================
Model: Organika/sdxl-detector
Detects: SDXL, Midjourney, DALL-E, Stable Diffusion images

DIFFERENCE FROM DEEPFAKE DETECTION:
- Deepfake = Real photo with face swapped/manipulated
- AI Image = Entirely generated by AI, no real photo base

HOW AI IMAGES ARE DIFFERENT:
- Subtle texture patterns from diffusion process
- Certain color distributions
- Sometimes weird details (hands, text, reflections)
- Consistent "AI aesthetic" artifacts
"""

import torch
from transformers import pipeline
from PIL import Image
import hashlib
import io
from typing import Union


class AIImageDetectionService:
    """
    Service to detect AI-generated images.
    
    This catches images made by:
    - Stable Diffusion / SDXL
    - Midjourney
    - DALL-E
    - Other diffusion models
    
    Usage:
        service = AIImageDetectionService()
        result = service.detect("ai_art.png")
        print(result['ai_probability'])  # e.g., 94.3
    """
    
    MODEL_NAME = "Organika/sdxl-detector"
    
    def __init__(self):
        """Initialize the service"""
        
        # pipeline() automatically handles GPU if available
        self.classifier = None
        self._loaded = False
        
        # Check device for logging
        self.device = "cuda" if torch.cuda.is_available() else "cpu"
        print(f"🖼️ AIImageDetectionService initialized (device: {self.device})")
    
    def load(self):
        """Load the image classification pipeline"""
        
        if self._loaded:
            return
        
        print(f"⏳ Loading AI image model: {self.MODEL_NAME}")
        
        # Hugging Face pipeline makes this super easy!
        # It automatically:
        # - Downloads the model
        # - Sets up preprocessing
        # - Handles inference
        self.classifier = pipeline(
            "image-classification",  # Task type
            model=self.MODEL_NAME,
            device=0 if torch.cuda.is_available() else -1  # 0=GPU, -1=CPU
        )
        
        self._loaded = True
        print("✅ AI image model loaded!")
    
    def detect(self, image: Union[str, bytes, Image.Image]) -> dict:
        """
        Detect if an image is AI-generated.
        
        Args:
            image: File path, bytes, or PIL Image
            
        Returns:
            dict with ai_probability, real_probability, classification
        """
        
        self.load()
        
        # =====================================================
        # Step 1: Load image
        # =====================================================
        
        if isinstance(image, str):
            img = Image.open(image).convert("RGB")
            with open(image, 'rb') as f:
                content_hash = hashlib.sha256(f.read()).hexdigest()
                
        elif isinstance(image, bytes):
            img = Image.open(io.BytesIO(image)).convert("RGB")
            content_hash = hashlib.sha256(image).hexdigest()
            
        elif isinstance(image, Image.Image):
            img = image.convert("RGB")
            img_bytes = io.BytesIO()
            img.save(img_bytes, format='PNG')
            content_hash = hashlib.sha256(img_bytes.getvalue()).hexdigest()
        else:
            raise ValueError("Image must be file path, bytes, or PIL Image")
        
        # =====================================================
        # Step 2: Run inference
        # =====================================================
        # The pipeline returns a list of predictions like:
        # [
        #   {'label': 'artificial', 'score': 0.943},
        #   {'label': 'real', 'score': 0.057}
        # ]
        
        results = self.classifier(img)
        
        # =====================================================
        # Step 3: Parse results
        # =====================================================
        # Different models use different label names, so we
        # check for common patterns
        
        ai_prob = 0.0
        real_prob = 0.0
        
        for result in results:
            label = result['label'].lower()
            score = result['score'] * 100  # Convert to percentage
            
            # Check if this is the "AI" class
            if any(word in label for word in ['artificial', 'ai', 'fake', 'generated', 'synthetic']):
                ai_prob = round(score, 2)
            # Check if this is the "Real" class
            elif any(word in label for word in ['real', 'human', 'natural', 'authentic']):
                real_prob = round(score, 2)
        
        # If model only returns one probability, infer the other
        if ai_prob > 0 and real_prob == 0:
            real_prob = round(100 - ai_prob, 2)
        elif real_prob > 0 and ai_prob == 0:
            ai_prob = round(100 - real_prob, 2)
        
        # =====================================================
        # Step 4: Classify
        # =====================================================
        
        if ai_prob > 70:
            classification = "ai_generated"
        elif ai_prob < 30:
            classification = "real"
        else:
            classification = "uncertain"
        
        confidence = round(abs(ai_prob - 50) * 2, 2)
        
        return {
            "content_type": "image",
            "detection_type": "ai_generated",
            "content_hash": content_hash,
            "ai_probability": ai_prob,
            "real_probability": real_prob,
            "classification": classification,
            "confidence": confidence,
            "detection_model": "sdxl-detector",
            "model_info": "Detects SDXL, Midjourney, DALL-E"
        }


# =====================================================
# Test
# =====================================================

if __name__ == "__main__":
    print("\n🖼️ AI Image Detection Service")
    print("="*50)
    print("To test, you need an image file.")
    print("Usage:")
    print("  service = AIImageDetectionService()")
    print("  result = service.detect('path/to/image.jpg')")
    print("  print(result)")